# docker-compose-pgsql.yaml
version: "3.8"

services:
  db:
    image: postgres:17
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bidpazar
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
